org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.238
neo_version_range=[21.1.193,)
loader_version_range=[1,)

mod_id=jei_plus_plus
mod_name=JEI++
mod_license=ARR
mod_version=1.0.4-1.21.1
mod_group_id=com.lingmu0
mod_authors=lingmu0
mod_description=Client-side JEI navigation and bookmark improvements.

jei_version=19.54.0.427
jei_version_range=[19.27.0,)
